spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/stocks"
    username: postgres
    password:  admin
      # security:
      #  oauth2:
      #   client:
      #    registration:
      #     google:
      #      clientId: 807427377963-562hbttj9aeupq1ho0l1t16rfj9j803l.apps.googleusercontent.com
      #     clientSecret: LMR8F0v7apjWWsYFwBH5zClZ
      #    scope:
      #     - email
      #    - profile

